### PR TITLE
Added Continued Conversation Guide

### PR DESCRIPTION
**Pull request by AveyBD**
This Module enable my devices to have continued conversation. i have added the guide.

### CODE REVIEW

**Comment by heykush** [comment]
But on my device continue conversation not working. Redmi note 5 vince - PE plus

**Comment by AveyBD** [comment]
> But on my device continue conversation not working. Redmi note 5 vince - PE plus

You have to select English US as language and You cant have any gsuite account.

**Comment by heykush** [comment]
> > But on my device continue conversation not working. Redmi note 5 vince - PE plus
> 
> You have to select English US as language and You cant have any gsuite account.

yes i on English US as language and not have gsuite account too. But when i switched to march prop, continue cov. start working, must be issue in prop code

**Comment by ayush5harma** [comment]
> > > But on my device continue conversation not working. Redmi note 5 vince - PE plus
> > 
> > 
> > You have to select English US as language and You cant have any gsuite account.
> 
> yes i on English US as language and not have gsuite account too. But when i switched to march prop, continue cov. start working, must be issue in prop code

Refer https://github.com/ayush5harma/P4XLProps/issues/10#issuecomment-701909812
Switching to March prop as you describe did what exactly it does when you  clear google app's cache. 
And you should always choose props matching to the system security patch version of your custom/stock pixel ROM..
Prop and system security patch mismatch will lead to CTS failure in safetynet causing you trouble with banking and some other apps.

**Pull request merged**
